language: node_js

node_js:
  - '4.2'

cache:
  directories:
    - node_modules

sudo: false

branches:
  except:
    - gh-pages

deploy:
  skip_cleanup: true
  provider: script
  script: git subtree push --prefix site origin gh-pages
  on:
    branch: master
